### ISSUE TITLE
`setQueryEditorHelp is not a function` when selecting datasource

### ISSUE THREAD

**Issue by PythonFZ** [haohanyang/mongodb-datasource#38]
When adding the `MongoDB` datasource I get the following error

```
(intermediate value).setConfigEditor(...).setQueryEditor(...).setQueryEditorHelp is not a function Evaluating http://nuc:28300/public/plugins/haohanyang-mongodb-datasource/module.js Loading plugins/haohanyang-mongodb-datasource/module
```

I am running the grafana via `docker-compose` as

```yaml
  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
     - '28300:3000'
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-mongodb-datasource
    volumes:
      - grafana-storage:/var/lib/grafana
      - grafana-mongodb-datasource:/var/lib/grafana/plugins/haohanyang-mongodb-datasource
```

with `Grafana v7.2.2 (ad9d408ac2)`.

When trying to remove the datasource I also get `Missing valid datasource id`.
I was following https://github.com/haohanyang/mongodb-datasource?tab=readme-ov-file#full-steps where I started the container first, then inside the container downloaded and unzipped the release. The binaries are executable and neither `root` nor `grafana` ownership solved the issue.
