### ISSUE TITLE
grafana Plugin Error in connection string

### ISSUE THREAD

**Issue by mariyarabartgenu** [haohanyang/mongodb-datasource#39]
Hi, I recently implemented this plugin and it works fine for me with my local grafana and mongodb database.

jsonData:
    host: ems-mongodb-node*
    port: ****
    database: *******
    authType: auth-none 

This is my json connection string in my datasource.yaml file

But when i try to push this to my live env, i dnt have host and port info , rather i have mongo+srv://` connection string . How to give this uri directly without host and port. Also this URI contains 3 replica sets. 

Below is my live connection string ..

mongodb://${mongodbAtlasUsername}:${mongodbAtlasPassword}@ac-3busccu-shard-00-00.kcxvtxi.mongodb.net:27017,ac-3busccu-shard-00-02.kcxvtxi.mongodb.net:27017,ac-3busccu-shard-00-01.kcxvtxi.mongodb.net:27017/admin?ssl=true

when i try to give only the first primary node details , It shows below error .

How to give this in my plugin connection string . Please help on this

**Comment by mariyarabartgenu** [comment]
<img width="951" alt="Image" src="https://github.com/user-attachments/assets/d0856bf5-8df7-44aa-ad60-3c837a820bf5" />

**Comment by haohanyang** [comment]
From your screenshot I saw you didn’t select ‘mongodb+srv’ scheme. You
should click it and try again

**Comment by mariyarabartgenu** [comment]
> From your screenshot I saw you didn’t select ‘mongodb+srv’ scheme. You
> should click it and try again
> […](#)

yes tried the same but no response . can you tell me how to give in my yaml file for srv connection string

![Image](https://github.com/user-attachments/assets/ef7243f5-3aff-42a0-9a42-c1cb95a6300c)

**Comment by mariyarabartgenu** [comment]
![Image](https://github.com/user-attachments/assets/18fd79a4-e574-4459-bc97-7c28828df2ff)

**Comment by mariyarabartgenu** [comment]
After tried the srv scheme still the error pop up . can you tell me how to give in my yaml file for srv connection string

**Comment by haohanyang** [comment]
I created a (free) mongo atlas cluster and the connection successful:

```yaml
apiVersion: 1

datasources:
  - name: 'mongodb-datasource'
    type: 'haohanyang-mongodb-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      host: default-cluster.4o9tx3a.mongodb.net
      connectionStringScheme: dns_seed_list
      port:
      database: test
      authType: auth-username-password
      username: user
    secureJsonData:
      password: ***

```

<img width="846" alt="Image" src="https://github.com/user-attachments/assets/d5fab905-46db-464c-9d03-4634b3e582c2" />
