### ISSUE TITLE
Unable to Install Unsigned Plugin "haohanyang-mongodb-datasource" on grafana/otel-lgtm

### ISSUE THREAD

**Issue by FractalMind** [haohanyang/mongodb-datasource#42]
I am trying to install the unsigned plugin haohanyang-mongodb-datasource on the grafana/otel-lgtm Docker image but cannot get it to load.

The same setup works fine with the grafana/grafana image (Grafana v11.5.1), but with grafana/otel-lgtm (same Grafana version), the plugin does not load.

Steps to reproduce:

Run the following docker-compose.yml:

``` yaml
version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "haohanyang-mongodb-datasource"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins

  grafana-otel:
    image: grafana/otel-lgtm
    container_name: grafana-otel
    restart: always
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "haohanyang-mongodb-datasource"
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/plugins:/var/lib/grafana/plugins

```
Install the plugin manually or ensure it's in ./grafana/plugins.
Start the services and check the Grafana plugin list (Settings -> Plugins).
Expected Behavior:
The plugin should be available in grafana/otel-lgtm just like it is in grafana/grafana.

Actual Behavior:
The plugin loads correctly in grafana/grafana, but does not appear in grafana/otel-lgtm.

Additional Context:

Grafana version: v11.5.1 (c6c701cf5b)
Docker images tested:
✅ grafana/grafana → Plugin works
❌ grafana/otel-lgtm → Plugin does not load

Possible reasons:
Does grafana/otel-lgtm have restrictions on unsigned plugins?
Is there an additional configuration required for custom plugins?
Would appreciate any insights on making this work in grafana/otel-lgtm. Thanks!

**Comment by haohanyang** [comment]
I guess the `grafana/otel-lgtm` has different place for plugin, which seems to be `/data/grafana/plugins`

**Comment by haohanyang** [comment]
I can confirm this config works
```yaml
services:
  grafana:
    image: grafana/otel-lgtm
    ports:
      - 3000:3000
    volumes:
      - ./path/to/plugins:/data/grafana/plugins # - ./mongodb-datasource:/data/grafana/plugins/haohanyang-mongodb-datasource
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: haohanyang-mongodb-datasource

```

<img width="739" alt="Image" src="https://github.com/user-attachments/assets/38dc4229-462d-4082-b176-52b90519b954" />
